27_URL Name dan Namespace/blog/urls.py
from django.conf.urls import url


from . import views

urlpatterns = [
	url(r'^khusus/(?P<input>[\w-]+)$',views.khusus, name="khusus"),
	url(r'^category/$',views.categoryPost, name="category"),
	url(r'^single/$',views.singlePost, name="single"),
	url(r'^$',views.index, name="index"),
]

27_URL Name dan Namespace/mywebsite/urls.py
from django.conf.urls import url,include
from django.contrib import admin


from . import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/',include('blog.urls', namespace='blog')),
    url(r'^$',views.index, name='index'),
]

27_URL Name dan Namespace/blog/models.py
from django.db import models

# Create your models here.

27_URL Name dan Namespace/blog/views.py
from django.shortcuts import render

# Create your views here.

def khusus(request,input):
	context = {
		'judul':input,
	}

	return render(request,'blog/index.html',context)

def categoryPost(request):
	context = {
		'judul':'category post',
	}

	return render(request,'blog/index.html',context)

def singlePost(request):
	context = {
		'judul':'single post',
	}

	return render(request,'blog/index.html',context)

def index(request):
	context = {
		'judul':'home blog',
	}

	return render(request,'blog/index.html',context)

27_URL Name dan Namespace/mywebsite/views.py
from django.shortcuts import render



def index(request):
	context = {
		'judul':'home'
	}

	return render(request,'index.html',context)

27_URL Name dan Namespace/blog/templates/blog/index.html
<!DOCTYPE html>
<html>
<head>
	<title>{{judul}}</title>
</head>
<body>
	<h1>{{judul}}</h1>
	<ul>
		<li><a href="{% url "index" %}" title="">home</a></li>
		<li><a href="{% url "blog:index" %}" title="">blog</a></li>
		<li><a href="{% url "blog:category" %}" title="">category</a></li>
		<li><a href="{% url "blog:single" %}" title="">single post</a></li>
		<li><a href="{% url "blog:khusus" input="otong"%}" title="">otong</a></li>
		<li><a href="{% url "blog:khusus" input="ucup"%}" title="">ucup</a></li>
	</ul>
</body>
</html>