50_Update View dan Delete View (Generic Class Based View)/blog/urls.py
from django.conf.urls import url
from django.views.generic import (
	ListView, 
	DetailView, 
	FormView
	)
from .views import (
	ArtikelListView, 
	ArtikelDetailView,
	ArtikelFormView,
	ArtikelCreateView1,
	ArtikelCreateView2,
	ArtikelUpdateView1,
	ArtikelUpdateView2,
	ArtikelDeleteView,
	)

from .models import Artikel
from .forms import ArtikelForm

urlpatterns = [
	url(r'^delete/(?P<pk>\d+)$', ArtikelDeleteView.as_view(), name='delete'),
	url(r'^update2/(?P<pk>\d+)$', ArtikelUpdateView2.as_view(), name='update2'),
	url(r'^update1/(?P<pk>\d+)$', ArtikelUpdateView1.as_view(), name='update1'),
	url(r'^create/$', ArtikelCreateView2.as_view(), name='create'),
	# url(r'^create/$', ArtikelCreateView1.as_view(), name='create'),
	# url(r'^create/$', ArtikelFormView.as_view(), name='create'),
	# url(r'^create/$', FormView.as_view(form_class=ArtikelForm, template_name='blog/create.html'), name='create'),
	url(r'^(?P<penulis>\w+)/(?P<page>\d+)$', ArtikelListView.as_view(), name='list'),
	url(r'^(?P<penulis>\w+)/$', ArtikelListView.as_view(), name='list'),
	url(r'^detail/(?P<slug>[\w-]+)$', ArtikelDetailView.as_view(model=Artikel), name='detail'),
	# url(r'^detail/(?P<slug>[\w-]+)$', DetailView.as_view(model=Artikel), name='detail'),
	# url(r'^$', ListView.as_view(model=Artikel), name = 'list'),
]

50_Update View dan Delete View (Generic Class Based View)/mywebsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
	url(r'^blog/', include('blog.urls', namespace = 'blog')),
    url(r'^admin/', admin.site.urls),
]

50_Update View dan Delete View (Generic Class Based View)/blog/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
# Create your models here.

class Artikel(models.Model):
	judul		= models.CharField(max_length=255)
	isi			= models.TextField()
	penulis		= models.CharField(max_length=255)
	publish		= models.DateTimeField(auto_now_add = True)
	update		= models.DateTimeField(auto_now = True)
	slug		= models.SlugField(blank=True, editable = False)

	def save(self):
		self.slug = slugify(self.judul)
		super(Artikel, self).save()

	def get_absolute_url(self):
		url_slug = {
			'slug':self.slug,
		}
		return reverse('blog:detail', kwargs=url_slug)

	def __str__(self):
		return "{}. {}".format(self.id, self.judul)

50_Update View dan Delete View (Generic Class Based View)/blog/forms.py
from django import forms

# model dari models.py
from .models import Artikel

class ArtikelForm(forms.ModelForm):
	class Meta:
		model = Artikel
		fields = [
			'judul',
			'isi',
			'penulis',
		]

50_Update View dan Delete View (Generic Class Based View)/blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy


from django.views.generic import (
	ListView, 
	DetailView,
	FormView,
	CreateView,
	UpdateView,
	DeleteView,
	)

from .models import Artikel
from .forms import ArtikelForm


class ArtikelDeleteView(DeleteView):
	model = Artikel
	# template_name = 'blog/delete_konfirmasi.html'
	success_url = reverse_lazy('blog:list',kwargs={'penulis':'all'})


class ArtikelUpdateView2(UpdateView):
	model = Artikel
	fields = [
		'isi',
	]

	extra_context = {
		'page_title':'update Artikel dengan update view 2',
	}

	def get_context_data(self, *args, **kwargs):
		kwargs.update(self.extra_context)
		return super().get_context_data(*args, **kwargs)


class ArtikelUpdateView1(UpdateView):
	form_class = ArtikelForm
	model = Artikel
	template_name = 'blog/create.html'

	extra_context = {
		'page_title':'update Artikel dengan update view 1',
	}

	def get_context_data(self, *args, **kwargs):
		kwargs.update(self.extra_context)
		return super().get_context_data(*args, **kwargs)

class ArtikelCreateView2(CreateView):
	model = Artikel
	fields = [
		'judul',
		'isi',
		'penulis',
	]

	# template akan diambil dari artikel_form, suffix = _form

	extra_context = {
		'page_title':'Tambah Artikel dengan create view',
	}

	def get_context_data(self, *args, **kwargs):
		kwargs.update(self.extra_context)
		return super().get_context_data(*args, **kwargs)


class ArtikelCreateView1(CreateView):
	form_class = ArtikelForm
	template_name = 'blog/create.html'

	extra_context = {
		'page_title':'Tambah Artikel dengan create view',
	}

	def get_context_data(self, *args, **kwargs):
		kwargs.update(self.extra_context)
		return super().get_context_data(*args, **kwargs)


class ArtikelFormView(FormView):
	form_class = ArtikelForm
	template_name = 'blog/create.html'
	# success_url = '/blog/all/'
	success_url = reverse_lazy('blog:list',kwargs={'penulis':'all'})
	extra_context = {
		'page_title':'Tambah Artikel',
	}

	def get_context_data(self,*args,**kwargs):
		kwargs.update(self.extra_context)
		return super().get_context_data(*args,**kwargs)

	def form_valid(self,form):
		# print(form.cleaned_data)
		form.save()
		return super().form_valid(form)


class ArtikelDetailView(DetailView):
	model = Artikel
	extra_context = {
		'page_title':'Detail Artikel',
	}

	def get_context_data(self, *args, **kwargs):
		self.kwargs.update(self.extra_context)
		artikel_lain = self.model.objects.exclude(slug=self.kwargs['slug'])
		self.kwargs.update({'artikel_lain':artikel_lain})
		kwargs = self.kwargs
		print(kwargs)
		return super().get_context_data(*args,**kwargs)



class ArtikelListView(ListView):
	model = Artikel
	ordering = ['publish']
	# paginate_by = 2
	extra_context = {
		'page_title':'Blog List',
	}

	def get_queryset(self):
		if self.kwargs['penulis'] != 'all':
			self.queryset = self.model.objects.filter(penulis__iexact = self.kwargs['penulis'])
			self.kwargs.update({
				'penulis':self.kwargs['penulis'],
				})
		return super().get_queryset()

	def get_context_data(self,*args,**kwargs):
		self.kwargs.update(self.extra_context)
		kwargs = self.kwargs
		return super().get_context_data(*args,**kwargs)

50_Update View dan Delete View (Generic Class Based View)/blog/templates/blog/artikel_confirm_delete.html
<!DOCTYPE html>
<html>
<head>
	<title>Delete</title>
</head>
<body>
	<form method='POST'>
		{% csrf_token %}
		<p>Apakah anda yakin ingin menghapus artikel <br><b>{{object}}</b></p>
		<input type="Submit" value="Ya">
		<a href="{% url 'blog:list' 'all'%}">
			<input type="button" value="Tidak">
		</a>
	</form>
</body>
</html>

50_Update View dan Delete View (Generic Class Based View)/blog/templates/blog/artikel_detail.html
<!DOCTYPE html>
<html>
<head>
	<title>{{page_title}}</title>
</head>
<body>
	<h1>{{page_title}}</h1>

	<h2>{{object.judul}}</h2>
	<span>Oleh: {{object.penulis}}, Ditulis : {{object.publish}}</span>
	<p>{{object.isi}}</p>
	<br>
	<a href="{% url 'blog:list' 'all' %}" title="">kembali</a>
	<a href="{% url 'blog:update1' object.pk %}" title="">update1</a>
	<a href="{% url 'blog:update2' object.pk %}" title="">update2</a>
	<br>
	<h3>Artikel lainnya:</h3>
	<ol>
		{% for artikel in artikel_lain %}
			<li>
				<a href="{% url 'blog:detail' artikel.slug %}" title="">{{artikel.judul}}</a> - oleh: {{artikel.penulis}}</li>		
		{% endfor %}
	</ol>
</body>
</html>

50_Update View dan Delete View (Generic Class Based View)/blog/templates/blog/artikel_form.html
<!DOCTYPE html>
<html>
<head>
	<title>Create</title>
</head>
<body>
	<h1>artikel_form.html</h1>
	<h1>{{page_title}}</h1>

	<form method='POST'>
		{% csrf_token %}
		<table>
			{{form.as_table}}
		</table>
		<button type="Submit">Kirim</button>
	</form>

</body>
</html>

50_Update View dan Delete View (Generic Class Based View)/blog/templates/blog/artikel_list.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<h1>{{page_title}}</h1>
	<a href="{% url 'blog:create' %}" title="">Tambah Artikel</a>
	<ol>
		{% for artikel in object_list %}
			<li>
				<a href="{% url 'blog:detail' artikel.slug %}" title="">{{artikel.judul}}</a> - oleh: {{artikel.penulis}} 
				<a href="{% url 'blog:delete' artikel.pk%}" title="">hapus</a></li>		
		{% endfor %}
	</ol>
	
	{% if is_paginated %}
		{% if page_obj.has_previous %}
			<a href="{% url 'blog:list' penulis page_obj.previous_page_number %}" title="">&laquo</a>
		{% else %}
			<span>&laquo</span>
		{% endif %}
		

		{% for i in paginator.page_range %}
			<a href="{% url 'blog:list' penulis i %}" title="">
				{{i}}
			</a>
		{% endfor %}


		{% if page_obj.has_next %}
			<a href="{% url 'blog:list' penulis page_obj.next_page_number %}" title="">&raquo</a>
		{% else %}
			<span>&raquo</span>
		{% endif %}
	{% endif %}

	{# {% if is_paginated %} #}
			{# <li>object_list = {{object_list}}</li> #}
			{# <li>is_paginated = {{is_paginated}}</li> #}
			{# <li>page_obj = {{page_obj}}</li> #}
			{# <li>page_obj.number = {{page_number}}</li> #}
			{# <li>page_obj.has_next = {{page_obj.has_next}}</li> #}
			{# <li>page_obj.has_previous = {{page_obj.has_previous}}</li> #}
			{# <li>page_obj.has_other_pages = {{page_obj.has_other_pages}}</li> #}
			{# <li>page_obj.next_page_number = {{page_obj.next_page_number}}</li> #}
			{# <li>page_obj.previous_page_number = {{page_obj.previous_page_number}}</li> #}
			{# <li>page_obj.start_index = {{page_obj.start_index}}</li> #}
			{# <li>page_obj.end_index = {{page_obj.end_index}}</li> #}
			{# <li>paginator.count = {{paginator.count}}</li> #}
			{# <li>paginator.num_pages = {{paginator.num_pages}}</li> #}
			{# <li>paginator.page_range = {{paginator.page_range}}</li> #}
		{# {% endif %} #}
</body>
</html>

50_Update View dan Delete View (Generic Class Based View)/blog/templates/blog/create.html
<!DOCTYPE html>
<html>
<head>
	<title>Create</title>
</head>
<body>
	<h1>create.html</h1>
	<h1>{{page_title}}</h1>

	<form method='POST'>
		{% csrf_token %}
		<table>
			{{form.as_table}}
		</table>
		<button type="Submit">Kirim</button>
	</form>

</body>
</html>

50_Update View dan Delete View (Generic Class Based View)/blog/templates/blog/delete_konfirmasi.html
<!DOCTYPE html>
<html>
<head>
	<title>Delete</title>
</head>
<body>
	<form method='POST'>
		{% csrf_token %}
		<p>Apakah anda yakin ingin menghapus artikel <br><b>{{object}}</b></p>
		<input type="Submit" value="Ya">
		<a href="{% url 'blog:list' 'all'%}">
			<input type="button" value="Tidak">
		</a>
	</form>
</body>
</html>

50_Update View dan Delete View (Generic Class Based View)/blog/templates/blog/index.html
<!DOCTYPE html>
<html>
<head>
	<title>{{page_title}}</title>
</head>
<body>
	<h1>{{page_title}}</h1>
</body>
</html>