30_Menggunakan class Form/contact/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$',views.index, name = 'index')
]

30_Menggunakan class Form/mywebsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin


from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^contact/', include('contact.urls',namespace='contact')),
    url(r'^admin/', admin.site.urls),
]

30_Menggunakan class Form/contact/models.py
from django.db import models

# Create your models here.

30_Menggunakan class Form/contact/forms.py
from django import forms

class ContactForm(forms.Form):
	nama 	= forms.CharField()
	alamat 	= forms.CharField()

30_Menggunakan class Form/contact/views.py
from django.shortcuts import render

# import form
from .forms import ContactForm
# Create your views here.

def index(request):

	contact_form = ContactForm()

	context = {
		'heading':'Contact Form',
		'contact_form':contact_form
	}

	if request.method == 'POST':
		context['nama'] = request.POST['nama']
		context['alamat'] = request.POST['alamat']

	return render(request,'contact/index.html', context)

30_Menggunakan class Form/mywebsite/views.py
from django.shortcuts import render


def index(request):
	context = {
		'heading':'Home Form',
	}

	if request.method == 'POST':
		print("ini adalah method post")
		context['nama'] = request.POST['nama']
		context['alamat'] = request.POST['alamat']
	else:
		print("ini adalah method get")

	print(request.POST)

	return render(request, 'index.html', context)

30_Menggunakan class Form/templates/index.html
<!DOCTYPE html>
<html>
<head>
	<title>{{heading}}</title>
</head>
<body>
	<h1>{{heading}}</h1>
	<ul>
		<li><a href="{% url 'index' %}">Home</a></li>
		<li><a href="{% url 'contact:index' %}">Contact</a></li>
	</ul>

	<form method='post'>
		{% csrf_token %}
		<label for="nama">Nama : </label>
		<input type="text" name="nama" id="nama">
		<br>
		<label for="alamat">Alamat : </label>
		<input type="text" name="alamat" id="alamat">
		<br>
		<button type="Submit">Kirim</button>

	</form>

	<h2>{{nama}}</h2>
	<h2>{{alamat}}</h2>
</body>
</html>